import test from 'node:test';
import assert from 'node:assert/strict';
import {normalizeEmail,emailKey,registerVerifiedPurchase,validatePurchase,PRODUCT} from '../netlify/lib/entitlements.mjs';
import {identityHook} from '../netlify/lib/legacy-identity-hook.mjs';
const purchase = {product:PRODUCT,price:20,currency:'USD',status:'APPROVED',email:' Buyer@Example.com ',orderId:'order-1'};
const request = body => new Request('https://example.com',{method:'POST',body:JSON.stringify(body)});
function store(){const data=new Map();return {data,async get(key,opts){assert.equal(opts.consistency,'strong');return data.get(key)||null;},async setJSON(key,value,opts){assert.equal(opts.onlyIfNew,true);if(data.has(key))return {modified:false};data.set(key,value);return {modified:true};}};}
test('normalización y hash estable, sin correo crudo',()=>{assert.equal(normalizeEmail(purchase.email),'buyer@example.com');assert.equal(emailKey(purchase.email),emailKey('buyer@example.com'));assert.match(emailKey(purchase.email),/^[a-f0-9]{64}$/);assert.throws(()=>normalizeEmail('invalido'));});
for(const [key,value] of [['product','other'],['price',0],['currency','ARS'],['status','PENDING']])test('rechazo '+key,()=>assert.throws(()=>validatePurchase({...purchase,[key]:value})));
test('persistencia idempotente y campos obligatorios',async()=>{const s=store();const first=await registerVerifiedPurchase(s,purchase,'2026-10-07T12:00:00Z');const next=await registerVerifiedPurchase(s,purchase,'2026-10-07T13:00:00Z');assert.deepEqual(first,next);assert.equal(s.data.size,1);assert.equal(first.status,'active');for(const key of ['email','name','result','source','orderedAt','grantedAt'])assert.ok(key in first);});
for(const nested of [false,true])test('payload '+(nested?'payload.user':'user')+' y respuesta exacta',async()=>{const s=store();await registerVerifiedPurchase(s,purchase);const user={email:'buyer@example.com',app_metadata:{custom:'kept',roles:['member','buyer','buyer']},private:'not returned'};const response=await identityHook(request(nested?{payload:{user}}:{user}),()=>s);assert.equal(response.status,200);assert.deepEqual(await response.json(),{app_metadata:{custom:'kept',roles:['member','buyer']}});});
test('sin compra, compra inactiva o producto distinto no conceden buyer',async()=>{for(const value of [null,{status:'revoked',product:PRODUCT,email:'buyer@example.com'},{status:'active',product:'other',email:'buyer@example.com'}]){const response=await identityHook(request({user:{email:'buyer@example.com'}}),()=>({get:async()=>value}));assert.deepEqual(await response.json(),{});}});
test('errores diferenciados, logs sin PII',async()=>{const logs=[];const cases=[[new Request('https://example.com',{method:'POST',body:'{' }),'payload_malformed',400],[request({}),'user_missing',400],[request({user:{email:'buyer@example.com'}}),'entitlement_lookup_failed',503]];for(const [req,error,status] of cases){const response=await identityHook(req,()=>{throw Error('backend secret');},value=>logs.push(value));assert.equal(response.status,status);assert.deepEqual(await response.json(),{error});}assert.deepEqual(logs,cases.map(c=>c[1]));});
test('fallo de escritura no informa éxito',async()=>{await assert.rejects(registerVerifiedPurchase({setJSON:async()=>{throw Error('offline');}},purchase));});
